### ISSUE TITLE
Error occurring with communication problem to node, connection renewal would be useful

### ISSUE THREAD

**Issue by mate-dev** [geoffwhittington/meshtastic-matrix-relay#56]
####  It would be useful to handle the error to renew the connection.
`
Exception in thread Thread-161: Traceback (most recent call last): File "/usr/lib/python3.11/[threading.py](http://threading.py/)", line 1038, in _bootstrap_inner [self.run](http://self.run/)() File "/usr/lib/python3.11/[threading.py](http://threading.py/)", line 1394, in run self.function(*self.args, **self.kwargs) File "/home/mate/meshtastic/meshtastic-matrix-relay/.pyenv/lib/python3.11/site-packages/meshtastic/mesh_[interface.py](http://interface.py/)", line 561, in callback self._sendToRadio(p) File "/home/mate/meshtastic/meshtastic-matrix-relay/.pyenv/lib/python3.11/site-packages/meshtastic/mesh_[interface.py](http://interface.py/)", line 619, in _sendToRadio self._sendToRadioImpl(toRadio) File "/home/mate/meshtastic/meshtastic-matrix-relay/.pyenv/lib/python3.11/site-packages/meshtastic/stream_[interface.py](http://interface.py/)", line 115, in _sendToRadioImpl self._writeBytes(header + b) File "/home/mate/meshtastic/meshtastic-matrix-relay/.pyenv/lib/python3.11/site-packages/meshtastic/tcp_[interface.py](http://interface.py/)", line 72, in _writeBytes self.socket.send(b) BrokenPipeError: [Errno 32] Broken pipe
`

**Comment by mate-dev** [comment]
![Screenshot_20230819_130548_JuiceSSH](https://github.com/geoffwhittington/meshtastic-matrix-relay/assets/67105053/18dfd0c6-e934-48ad-9f46-5d2ee97394fe)

**Comment by mate-dev** [comment]
Strace output:
`
....
13:06:58.740570 recvfrom(3, "", 1, 0, NULL, NULL) = 0 <0.000007>        13:06:58.740607 recvfrom(3, "", 1, 0, NULL, NULL) = 0 <0.000010>        13:06:58.740644 recvfrom(3, "", 1, 0, NULL, NULL) = 0 <0.000007>        13:06:58.740675 recvfrom(3, "", 1, 0, NULL, NULL) = 0 <0.000006>        13:06:58.740703 recvfrom(3, "", 1, 0, NULL, NULL) = 0 <0.000006>        13:06:58.740730 recvfrom(3, "", 1, 0, NULL, NULL) = 0 <0.000006>
....
`

**Comment by mate-dev** [comment]
Now I see that it is more of a bug with the meshtastic client itself.
